name: Create Bundle

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  create-bundle:
    runs-on: ubuntu-latest
    steps:
    - run: |
        mkdir -p dist
        echo "// Playwright Framework Bundle" > dist/bundle.js
        echo "module.exports = { version: '1.0.0' };" >> dist/bundle.js
        echo "Bundle created successfully"