name: Create Bundle

on:
  push:
    branches: [ main, master, develop ]
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  create-bundle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Create bundle script
        run: |
          mkdir -p dist
          echo "// Playwright Framework Bundle" > dist/bundle.js
          echo "// Generated: $(date)" >> dist/bundle.js
          echo "module.exports = {" >> dist/bundle.js
          echo "  version: '1.0.0'," >> dist/bundle.js
          echo "  name: 'playwright-framework'," >> dist/bundle.js
          echo "  description: 'Playwright Test Framework Bundle'" >> dist/bundle.js
          echo "};" >> dist/bundle.js
          echo "Bundle created successfully!"
      
      - name: Run linting
        run: npm run lint
        continue-on-error: true
      
      - name: Build package
        run: npm run build
      
      - name: Upload bundle artifact
        uses: actions/upload-artifact@v4
        with:
          name: framework-bundle
          path: dist/
      
      - name: Publish to NPM
        if: startsWith(github.ref, 'refs/tags/')
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}