name: Create Bundle

on:
  push:
    branches: [ main, master, develop ]
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  create-bundle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Check if scripts directory exists
        run: |
          if [ ! -d "scripts" ]; then
            echo "Creating scripts directory"
            mkdir -p scripts
          fi
      
      - name: Check if create-bundle.js exists
        run: |
          if [ ! -f "scripts/create-bundle.js" ]; then
            echo "Creating create-bundle.js script"
            cat > scripts/create-bundle.js << 'EOL'
            /**
             * Simple script to create a bundle
             */
            const fs = require('fs');
            const path = require('path');

            // Create dist directory if it doesn't exist
            const distDir = path.join(process.cwd(), 'dist');
            if (!fs.existsSync(distDir)) {
              fs.mkdirSync(distDir, { recursive: true });
            }

            // Create a simple bundle file
            const bundleContent = `
            /**
             * Playwright Framework Bundle
             * Generated: ${new Date().toISOString()}
             */
            module.exports = {
              version: require('../package.json').version,
              name: require('../package.json').name,
              description: require('../package.json').description
            };
            `;

            // Write the bundle file
            fs.writeFileSync(path.join(distDir, 'bundle.js'), bundleContent);

            console.log('Bundle created successfully!');
            EOL
            chmod +x scripts/create-bundle.js
          fi
      
      - name: Run linting
        run: npm run lint
        continue-on-error: true
      
      - name: Create bundle
        run: node scripts/create-bundle.js
      
      - name: Build package
        run: npm run build
      
      - name: Upload bundle artifact
        uses: actions/upload-artifact@v4
        with:
          name: framework-bundle
          path: dist/
      
      - name: Publish to NPM
        if: startsWith(github.ref, 'refs/tags/')
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}