name: Create Distribution Bundle

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  bundle:
    runs-on: ubuntu-latest
    steps:
    - run: |
        mkdir -p dist
        echo "// Distribution bundle" > dist/bundle.js
        echo "Distribution bundle created successfully"