name: Docker Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          load: true
          tags: playwright-framework:test
          cache-from: type=gha
          cache-to: type=gha,mode=max
      
      - name: Run tests
        run: |
          docker run --rm \
            -v ${{ github.workspace }}/test-results:/app/test-results \
            -v ${{ github.workspace }}/playwright-report:/app/playwright-report \
            -v ${{ github.workspace }}/allure-results:/app/allure-results \
            -v ${{ github.workspace }}/reports:/app/reports \
            -v ${{ github.workspace }}/visual-diffs:/app/visual-diffs \
            -e BASE_URL=${{ secrets.BASE_URL }} \
            -e API_URL=${{ secrets.API_URL }} \
            -e API_BASE_URL=${{ secrets.API_BASE_URL }} \
            -e TEST_USERNAME=${{ secrets.TEST_USERNAME }} \
            -e TEST_PASSWORD=${{ secrets.TEST_PASSWORD }} \
            -e NODE_ENV=production \
            -e CI=true \
            playwright-framework:test
      
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: |
            playwright-report/
            allure-results/
            reports/
      
      - name: Upload visual test diffs (if any)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: visual-diffs
          path: visual-diffs/