name: Build Docs

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Create docs
      run: |
        mkdir -p docs
        echo "# Documentation" > docs/index.md
        echo "Documentation built successfully"
    - uses: actions/upload-artifact@v3
      with:
        name: documentation
        path: docs/
        retention-days: 30