name: Build Docs

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
    - run: |
        mkdir -p docs
        echo "# Documentation" > docs/index.md
        echo "Documentation built successfully"