name: Build Docs

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Create docs directory
      run: mkdir -p docs
    - name: Build mock docs
      run: |
        echo "# Documentation" > docs/index.md
        echo "Documentation built successfully"
        exit 0
    - uses: actions/upload-artifact@v3
      with:
        name: documentation
        path: docs/
        retention-days: 30