name: Framework Validation

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:
    inputs:
      browser:
        description: 'Browser to run tests on'
        required: true
        default: 'chromium'
        type: choice
        options:
          - chromium
          - firefox
          - webkit
          - all

jobs:
  validate:
    name: Validate Framework
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Install Playwright browsers
        run: npx playwright install --with-deps
      
      - name: Create .env file
        run: |
          cat > .env << 'EOL'
          # Environment configuration
          API_BASE_URL=https://reqres.in
          API_GRAPHQL_PATH=/graphql
          BASE_URL=https://example.com
          API_KEY=123456
          OAUTH2_TOKEN=dummy-token
          
          # Login Credentials
          LOGIN_USERNAME=testuser
          LOGIN_PASSWORD=secure123
          TEST_USERNAME=testuser@example.com
          TEST_PASSWORD=password123
          
          # Playwright Runtime Settings
          NODE_ENV=test
          HEADLESS=true
          SLOWMO=0
          
          # CI Runtime Vars
          CI=true
          WORKERS=2
          EOL
      
      - name: Run framework health check
        run: node scripts/framework-health-check.js
      
      - name: Run framework validation tests
        run: npx playwright test --grep @validation
      
      - name: Generate validation report
        if: always()
        run: node scripts/generate-validation-dashboard.js
      
      - name: Upload validation report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: framework-validation-results
          path: |
            reports/validation/
            playwright-report/
          retention-days: 30
      
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results/
          retention-days: 7
      
      - name: Check test status
        if: always()
        run: |
          if [ -f "reports/validation/dashboard.html" ]; then
            if grep -q "Failed Tests.*0" "reports/validation/dashboard.html"; then
              echo "✅ Framework validation passed!"
              exit 0
            else
              echo "❌ Framework validation failed!"
              exit 1
            fi
          else
            echo "❌ Validation report not generated!"
            exit 1
          fi