name: Local Test
on: [push, workflow_dispatch]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check Node version
        run: node --version
      - name: List files
        run: ls -la
      - name: Check package.json
        run: cat package.json | grep name