name: Release Branch

on:
  push:
    branches: ['release/*']

jobs:
  prepare-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      
      - run: npm ci --legacy-peer-deps
      - run: npm test
      - run: npm run build
      
      - name: Extract version from branch
        id: version
        run: echo "VERSION=${GITHUB_REF#refs/heads/release/}" >> $GITHUB_OUTPUT
      
      - name: Update version in package.json
        run: npm version ${{ steps.version.outputs.VERSION }} --no-git-tag-version
      
      - name: Create PR to main
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: release/${{ steps.version.outputs.VERSION }}
          base: main
          title: "Release v${{ steps.version.outputs.VERSION }}"
          body: "Automated release PR for v${{ steps.version.outputs.VERSION }}"