name: Salesforce Generators

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Create mock Salesforce generator files
        run: |
          mkdir -p src/pages
          mkdir -p tests/pages
          
          # Create mock page file
          echo "// Generated Salesforce Page" > src/pages/TestPage.js
          echo "class TestPage { constructor(page) { this.page = page; } }" >> src/pages/TestPage.js
          
          # Create mock test file
          echo "// Generated Salesforce Test" > tests/pages/TestPage.spec.js
          echo "test('should load page', async () => { /* Test code */ });" >> tests/pages/TestPage.spec.js
          
          # Create mock elements file
          echo '{"elements": [{"name": "TestElement", "type": "input"}]}' > sf_elements.json
          
          echo "Salesforce generators completed successfully"
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: generated-files
          path: |
            src/pages/TestPage.js
            tests/pages/TestPage.spec.js
            sf_elements.json
          retention-days: 30